-- Schema:

USE dermabase;





-- The following is a list of diagnoses that will be inserted and predefined in the database. Adjust the records according to your preferences if needed.

INSERT INTO `diagnoses` (`name`) VALUES
('Acanthosis Nigricans'),
('Acne'),
('Acne Conglobata'),
('Acne Keloidalis'),
('Acne Nodulocystic'),
('Actinic Keratosis'),
('Alopecia Areata'),
('Alopecia Totalis'),
('Alopecia Universalis'),
('Angioedema'),
('Angiokeratoma'),
('Ashy Dermatosis'),
('Atopic Dermatitis'),
('BCC'),
('BUllous Pemphigoid'),
('Burn'),
('CARP'),
('Canities'),
('Cellulitis'),
('Comedonal Acne'),
('Common Wart'),
('Corn'),
('CSVV'),
('Dandruff'),
('Dermatophyte'),
('Dermatomyositis'),
('DH'),
('Diaper rash'),
('DLE'),
('Drug Eruption'),
('Eczema'),
('Ecchymosis'),
('Erythema Multiforme'),
('Erythrasma'),
('Erythrodermia'),
('Eyebrow Loss'),
('Eye Shiner'),
('Epidermal Cyst'),
('Favre-Rochoshutt'),
('Folliculitis'),
('Freckle'),
('Freckle'),
('Furuncle'),
('FXD'),
('Fuliclitis Decalvans'),
('G.A'),
('Genital Wart'),
('Glossitis'),
('Granuloma Faciale'),
('HSV Type 1'),
('HSV Type 2'),
('Hair loss'),
('Halo Nevus'),
('Hemangioma'),
('Hypersensitivity'),
('Hirsutism'),
('Hydrocystoma Apocrine'),
('Hydrocystoma Eccrine'),
('Hydradenitis Supporativa'),
('Hyperhydrosis'),
('Ichthyosis'),
('Infected Eczema'),
('Ingrown Toe Nail'),
('Intertrigo'),
('Intertrigo'),
('Jessners Lymphocytic Infiltration'),
('Juvenile Plantar Dermatosis'),
('Keratosis Pilaris'),
('Impetigo'),
('Keloid'),
('Lentigo'),
('Lentigo Maligna'),
('Lichen Amyloidosis'),
('Lichen Planus'),
('Lichenification'),
('LPP'),
('LSA'),
('LSC'),
('Macular Amyloidosis'),
('Malignant Malanoma'),
('Mastocytoma'),
('MF'),
('Multiple Bites'),
('Melasma'),
('Milia'),
('Molluscum Contagiosum'),
('Morphea'),
('Nevus'),
('Nevus Anemicus'),
('Nevus Depigmentosus'),
('Onychomycosis'),
('Orf'),
('PAN'),
('P.Albae'),
('PCOD'),
('Pediculosis'),
('Pemphigus Folliaceous'),
('Pemphigus Vulgaris'),
('Periorbital Darkness'),
('Photosensitivity'),
('Phytophotodermatitis'),
('PIH'),
('Pitted Keratolysis'),
('Pityriasis Rosea'),
('PLC'),
('PLEVA'),
('Port Wine Stain'),
('PPD'),
('PPK'),
('Prurigo Nodularis'),
('Pruritus'),
('Pseudoxanthoma Elasticum'),
('Psoriasis'),
('Pustular Psoriasis'),
('PUPPP'),
('Pyogenic Granuloma'),
('Recurrent Aphtosis'),
('Recurrent HSV'),
('Rosacea'),
('Scabies'),
('Scar'),
('Scar Acne'),
('Scar Atrophic'),
('Scar Hypertrophic'),
('SCC'),
('Sclerodermia'),
('Sebaceous hyperplasia'),
('Seborrheic Dermatitis'),
('Seborrheic Keratosis'),
('SLE'),
('Skin tag'),
('Stasis Dermatitis'),
('Steatocystoma Multiplex'),
('Stomatitis'),
('Striae Alba'),
('Striae Rubra'),
('T. Versicolor'),
('Tinea Amiantacea'),
('Tinea Capitis'),
('Trichostasis spinolusa'),
('Ulcer'),
('Urticaria'),
('Urticarial Vasculitis'),
('Vasculitis'),
('Vitiligo'),
('Xerosis'),
('Zona');