-- Schema:

USE dermabase;





-- The following is a list of treatments that will be inserted and predefined in the database. Adjust the records according to your preferences if needed.

INSERT INTO `treatments` (`name`) VALUES
('Accutane 10 mg'),
('Accutane 20 mg'),
('Acitretin 10 mg'),
('Acitretin 25 mg'),
('Acyclovir'),
('Adapalen'),
('AHA'),
('Alprazolam'),
('Antdandruff Shampoo'),
('Antihistamine'),
('Apremilast'),
('Azaram'),
('Azithromycin'),
('BPO'),
('Cefalexin'),
('Celcept'),
('Cinora'),
('Clotrimazole'),
('Cyclosporin'),
('Doxycyclin'),
('Drop Salicylic Acid Compound'),
('Ferrglobin'),
('Finpecia 1'),
('Finpecia 5'),
('Fluconazole'),
('Fucidin'),
('Gabapentin'),
('Griseofulvin 125'),
('HQ 200 mg'),
('Infliximab'),
('Itraconazole'),
('Meladinine'),
('Metronidazole'),
('Metrogel'),
('Mometason'),
('Minocycline'),
('Minoxidil 2%'),
('Minoxidil 5%'),
('Mopirucin'),
('MTX'),
('PABA'),
('Permethrin'),
('Prednisolon 5'),
('Prednisolon 50'),
('Propranolol 10'),
('Tacril'),
('Tetracyclin 250'),
('Terbinafine 250'),
('Topical Clotrisone'),
('Topical steroid'),
('Tofacitinib'),
('Valacyclovir'),
('Vit. C'),
('Voriconazole');